export const REQUEST_GENRES = 'REQUEST_GENRES'
export const RECEIVE_GENRES = 'RECEIVE_GENRES'
export const FILTER_GENRES = 'FILTER_GENRES'

export const REQUEST_GENRE = 'REQUEST_GENRE'
export const RECEIVE_GENRE = 'RECEIVE_GENRE'
export const REQUEST_GENRE_SIMILAR = 'REQUEST_GENRE_SIMILAR'
export const RECEIVE_GENRE_SIMILAR = 'RECEIVE_GENRE_SIMILAR'
export const REQUEST_GENRE_TOP_ARTISTS = 'REQUEST_GENRE_TOP_ARTISTS'
export const RECEIVE_GENRE_TOP_ARTISTS = 'RECEIVE_GENRE_TOP_ARTISTS'
export const REQUEST_GENRE_TOP_ALBUMS = 'REQUEST_GENRE_TOP_ALBUMS'
export const RECEIVE_GENRE_TOP_ALBUMS = 'RECEIVE_GENRE_TOP_ALBUMS'

export const REQUEST_ARTISTS = 'REQUEST_ARTISTS'
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS'

export const REQUEST_ARTIST = 'REQUEST_ARTIST'
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST'
export const SELECT_READ_MORE_ARTIST = 'SELECT_READ_MORE_ARTIST'

export const REQUEST_ALBUMS = 'REQUEST_ALBUMS'
export const RECEIVE_ALBUMS = 'RECEIVE_ALBUMS'

export const REQUEST_ALBUM = 'REQUEST_ALBUM'
export const RECEIVE_ALBUM = 'RECEIVE_ALBUM'
export const SELECT_READ_MORE_ALBUM = 'SELECT_READ_MORE_ALBUM'

export const HIDE_TOP_SECTION = 'TOP_SECTION_HIDE'