export const REQUEST_GENRES = 'REQUEST_GENRES'
export const RECEIVE_GENRES = 'RECEIVE_GENRES'
export const SELECT_SHOW = 'SELECT_SHOW'
export const FILTER_GENRES = 'FILTER_GENRES'

export const REQUEST_GENRE = 'REQUEST_GENRE'
export const RECEIVE_GENRE = 'RECEIVE_GENRE'

export const REQUEST_ARTISTS = 'REQUEST_ARTISTS'
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS'

export const REQUEST_ARTIST = 'REQUEST_ARTIST'
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST'
export const SELECT_READ_MORE_ARTIST = 'SELECT_READ_MORE_ARTIST'